### ISSUE TITLE
Can't Use Gradle Dependency or JAR

### ISSUE THREAD

**Issue by eygraber** [pusher/pusher-java-client#53]
If I include pusher as a dependency in my project, the build fails because it cannot find websockets 1.3.1 If I use the JAR, it won't build because you include GSON as a part of your project, and that conflicts with the GSON dependency I have in my project. 

I'd love to use pusher, but users shouldn't have to resort to building the project themselves in order to get it to work, especially with the proliferation of platforms like Gradle.

**Comment by eygraber** [comment]
Looks like the GSON issue is because I had pulled down the jar with dependencies.

As far as gradle and websockets 1.3.1, don't you include that as a submodule? Is the dependency still necessary from a gradle point of view? If not you should remove it, because it will block anyone trying to use pusher through gradle. And if it is necessary, then you probably shouldn't publish to maven until you figure out how to package websockets with it.

**Comment by tir38** [comment]
I don't even see websockets version 1.3.1
https://github.com/TooTallNate/Java-WebSocket/releases
http://search.maven.org/#browse%7C651207691

**Comment by a54studio** [comment]
Thx, helped me out.
